"""empty message

Revision ID: 2827a92c31a9
Revises: 38b903e51622
Create Date: 2019-01-26 20:56:13.570440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2827a92c31a9'
down_revision = '38b903e51622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'designation',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('instrument', sa.Column('description', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_instrument_description'), 'instrument', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_description'), table_name='instrument')
    op.drop_column('instrument', 'description')
    op.alter_column('document', 'designation',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
