"""empty message

Revision ID: 38b903e51622
Revises: 919bba41db14
Create Date: 2019-01-26 11:10:04.231683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b903e51622'
down_revision = '919bba41db14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('designation', sa.String(length=100), nullable=True))
    op.add_column('document', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_designation'), 'document', ['designation'], unique=False)
    op.drop_constraint('document_ibfk_2', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'user', ['uploader_id'], ['id'])
    op.drop_column('document', 'owner_id')
    op.add_column('workstation', sa.Column('scope', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workstation', 'scope')
    op.add_column('document', sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_ibfk_2', 'document', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_document_designation'), table_name='document')
    op.drop_column('document', 'uploader_id')
    op.drop_column('document', 'designation')
    # ### end Alembic commands ###
