"""empty message

Revision ID: 9b38bed025e6
Revises: 2827a92c31a9
Create Date: 2019-01-27 00:40:18.917673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b38bed025e6'
down_revision = '2827a92c31a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('data_fields_json', sa.Text(), nullable=True))
    op.add_column('instrument', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('instrument', sa.Column('last_maintenance_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument', 'last_maintenance_interval')
    op.drop_column('instrument', 'last_maintenance_date')
    op.drop_column('instrument', 'data_fields_json')
    # ### end Alembic commands ###
